Repository Please-Hug/HugmeEXP_Backend, pull requests merged in 2025-08, with the labels that each got.

#45 [feat] 관리자 예약 관리 기능 구현
  src/main/java/org/example/hugmeexp/domain/studyRoom/controller/AdminReservationController.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/repository/StudyRoomReservationRepository.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/service/AdminReservationService.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/service/StudyRoomReservationService.java
  src/test/java/org/example/hugmeexp/domain/studyRoom/service/AdminReservationServiceTest.java
Labels: 기능 개발

#52 즐겨찾기 기능 구현
  src/main/java/org/example/hugmeexp/domain/recruitment/controller/RecruitmentBookmarkController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/entity/RecruitmentBookmark.java
  src/main/java/org/example/hugmeexp/domain/recruitment/exception/DuplicateRecruitmentBookmarkException.java
  src/main/java/org/example/hugmeexp/domain/recruitment/exception/RecruitmentBookmarkNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/RecruitmentBookmarkRepository.java
  src/main/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentBookmarkService.java
  src/main/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentService.java
  src/main/java/org/example/hugmeexp/global/common/exception/code/ErrorStatus.java
  src/test/http/recruitment.http
  src/test/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentBookmarkServiceTest.java
Labels: 기능 개발

#54 erd 기준으로 entity, dto 변경
  src/main/java/org/example/hugmeexp/domain/praise/controller/CommentController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/controller/RecruitmentBookmarkController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/controller/RecruitmentController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/CompanyListResponse.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentCompanySearchResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentDetailResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentSearchConditionDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/entity/Company.java
  src/main/java/org/example/hugmeexp/domain/recruitment/entity/Recruitment.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/RecruitmentRepository.java
  src/test/http/recruitment.http
  src/test/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 리팩토링

#56 필터 조건 조회 기능 구현
  src/main/java/org/example/hugmeexp/domain/recruitment/controller/RecruitmentController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/EducationOptionDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentDetailResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentFilterResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/SalaryRangeDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/TagDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/TechStackDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/TagItemRepository.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/TechItemRepository.java
  src/main/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentService.java
  src/test/http/recruitment.http
  src/test/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 기능 개발

#63 [refactor] 스터디 룸 성능 개선
  src/main/java/org/example/hugmeexp/HugmeExpApplication.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/entity/StudyHall.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/entity/StudyRoom.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/service/StudyHallService.java
Labels: 리팩토링, 성능 개선

#60 [Feat] StudyRoom Reservation TestCode 작성 및 미흡부분 개선
  build.gradle
  src/main/java/org/example/hugmeexp/HugmeExpApplication.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/controller/StudyRoomReservationController.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/dto/request/ReservationCreateDto.java
  src/main/java/org/example/hugmeexp/domain/studyRoom/service/StudyRoomReservationService.java
  src/test/java/org/example/hugmeexp/domain/studyRoom/service/StudyRoomReservationServiceTest.java
Labels: 기능 개발

#68 리스트 조회 기능 개선
  src/main/java/org/example/hugmeexp/domain/recruitment/controller/RecruitmentController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentService.java
  src/test/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 리팩토링

#70 필터 조건 기능 수정
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentSearchConditionDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentService.java
  src/test/http/recruitment.http
  src/test/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 버그, 리팩토링

#72 [Fix] 위도, 경도 공고 리스트 검색 오류 해결
  src/main/java/org/example/hugmeexp/domain/recruitment/controller/RecruitmentController.java
  src/main/java/org/example/hugmeexp/domain/recruitment/dto/RecruitmentSearchConditionDTO.java
  src/main/java/org/example/hugmeexp/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/org/example/hugmeexp/domain/recruitment/service/RecruitmentService.java
Labels: 버그
